# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
version: 2

reviews:
  auto_review:
    enabled: true
  review_profile: CHILL
  allow_review_on_draft: false

summaries:
  enabled: true
  placement: PR_BODY

fail_conditions:
  # Treat high severity issues as blockers
  high_severity_block: true

labels:
  # Apply STRICT profile when PR is labeled "strict"
  - label: strict
    review_profile: STRICT
  # Chill for docs/chore
  - label: docs
    review_profile: CHILL
  - label: chore
    review_profile: CHILL

comments:
  nits: true
  style_suggestions: true
  request_tests: true
  max_comments: 50

ignore:
  files:
    - "dist/**"
    - "vendor/**"
    - "**/*.sum"
    - "**/*.min.*"
    - ".claude/**"
    - ".coderabbit.yaml"  # do not review config changes themselves

ui:
  finishing_touches_checklist: true

