run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable:
    - typecheck
  enable:
    - errcheck
    - ineffassign
    - gosimple

# Exclude specific patterns  
issues:
  exclude:
    - "undefined: (yaml|progressbar)"
  exclude-rules:
    # Allow ignoring errors from progress bar best-effort UI calls in tests
    - path: cmd/(create|test)\.go
      linters:
        - errcheck
      text: 'bar\.(Add|Finish)\('

