run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - gosimple
  disable:
    - typecheck

# Keep default enabled linters; add exclusions only where necessary
issues:
  exclude-rules:
    # Allow ignoring errors from progress bar best-effort UI calls in tests
    - path: cmd/(create|test)\.go
      linters:
        - errcheck
      text: 'bar\.(Add|Finish)\('

