run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - gosimple

# Keep additional linter settings available for future tightening
linters-settings:
  typecheck:
    include-tests: true

# Keep default enabled linters; add exclusions only where necessary
issues:
  exclude-rules:
    # Allow ignoring errors from progress bar best-effort UI calls in tests
    - path: cmd/(create|test)\.go
      linters:
        - errcheck
      text: 'bar\.(Add|Finish)\('
    # Allow typecheck on specific test-only yaml usage if still flagged
    - path: cmd/restore_test\.go
      linters:
        - typecheck
      text: "yaml"
    - path: internal/config/config\.go
      linters:
        - typecheck
      text: 'undefined: yaml'
    - path: cmd/config\.go
      linters:
        - typecheck
      text: 'undefined: yaml'
    - path: cmd/create\.go
      linters:
        - typecheck
      text: 'undefined: progressbar'

