# 7EP-0018 Supporting File: GitHub Actions Deployment
# Save this as .github/workflows/blog.yml

name: Deploy Blog

on:
  push:
    branches: [main]
    paths: ['blog/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: |
          cd blog
          go mod tidy
      
      - name: Build blog
        run: |
          cd blog
          mkdir -p public/static
          go run generator.go
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./blog/public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

# Alternative: Deploy to custom domain
# Uncomment and configure if using custom domain like blog.7zarch.dev
#      - name: Deploy to Pages (Custom Domain)
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./blog/public
#          cname: blog.7zarch.dev