name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
        
    - name: Download dependencies
      run: make deps
      
    - name: Build binary
      run: make build
      
    - name: Verify binary exists
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          test -f 7zarch-go.exe || test -f 7zarch-go
        else
          test -f 7zarch-go
        fi
        
    - name: Run binary version check
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          if test -f 7zarch-go.exe; then
            ./7zarch-go.exe --version || true
          else
            ./7zarch-go --version || true
          fi
        else
          ./7zarch-go --version || true
        fi
        
  build-all:
    name: Cross-Platform Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
        
    - name: Download dependencies
      run: make deps
      
    - name: Build all platforms
      run: make build-all
      
    - name: List built artifacts
      run: ls -la dist/
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/
        retention-days: 7